### ISSUE TITLE
Not Found error

### ISSUE THREAD

**Issue by mmoayyed** [lalitkapoor/github-changes#50]
github-changes -o Jasig -r cas -b 4.0.1 -k TOKEN -a

```
{ [Error: Not Found]
  domainEmitter: 
   { domain: 
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        members: [] },
     _events: { end: [Object], data: [Function] },
     _maxListeners: 10,
     writable: false,
     readable: true,
     paused: false,
     autoDestroy: true,
     push: [Function],
     queue: [Function],
     end: [Function],
     destroy: [Function],
     pause: [Function],
     resume: [Function] },
  domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [] },
  domainThrown: false }
Error: Not Found
    at Request._callback (/usr/local/lib/node_modules/github-changes/node_modules/github-commit-stream/index.js:59:37)
    at Request.self.callback (/usr/local/lib/node_modules/github-changes/node_modules/github-commit-stream/node_modules/request/index.js:148:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/github-changes/node_modules/github-commit-stream/node_modules/request/index.js:886:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/github-changes/node_modules/github-commit-stream/node_modules/request/index.js:837:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:486:13)
```

**Comment by JoseCage** [comment]
I have the same error.. How you solve??
