### ISSUE TITLE
Error: 504: Gateway Timeout - index.js:779:26

### ISSUE THREAD

**Issue by simov** [lalitkapoor/github-changes#56]
:wave: 

I'm using the following commend to generate the changelog for the request repository

``` bash
github-changes -o request -r request --token [TOKEN] --verbose --file CHANGELOG.md --only-pulls --use-commit-body --date-format '(YYYY/MM/DD)'
```

And I'm constantly getting the following error:

``` bash
fetching commits
pulled commit data for tag -  v2.70.0
pulled commit data for tag -  v2.70.1
pulled commit data for tag -  v2.71.0
pulled commit data for tag -  v2.71.1
pulled commit data for tag -  v2.69.1
fetched 100 commits
pulled commit data for tag -  v2.56.1
pulled commit data for tag -  v2.57.0
pulled commit data for tag -  v2.55.1
pulled commit data for tag -  v2.56.0
pulled commit data for tag -  v2.55.0
pulled commit data for tag -  v2.54.1
pulled commit data for tag -  v2.54.0
pulled commit data for tag -  v2.53.1
pulled commit data for tag -  v2.53.0
pulled commit data for tag -  v2.52.1
pulled commit data for tag -  v2.52.0
pulled commit data for tag -  v2.51.1
pulled commit data for tag -  v2.51.0
pulled commit data for tag -  v2.50.1
pulled commit data for tag -  v2.49.1
pulled commit data for tag -  v2.50.0
pulled commit data for tag -  v2.49.0
pulled commit data for tag -  v2.48.1
pulled commit data for tag -  v2.46.1
pulled commit data for tag -  v2.47.1
pulled commit data for tag -  v2.48.0
pulled commit data for tag -  v2.47.0
pulled commit data for tag -  v2.46.0
pulled commit data for tag -  v2.45.1
pulled commit data for tag -  v2.45.0
pulled commit data for tag -  v2.44.1
pulled commit data for tag -  v2.44.0
pulled commit data for tag -  v2.43.1
pulled commit data for tag -  v2.43.0
pulled commit data for tag -  v2.42.1
pulled commit data for tag -  v2.42.0
pulled commit data for tag -  v2.41.0
pulled commit data for tag -  v2.40.0
pulled commit data for tag -  v2.41.1
pulled commit data for tag -  v2.40.1
pulled commit data for tag -  v2.39.1
pulled commit data for tag -  v2.39.0
pulled commit data for tag -  v2.38.1
pulled commit data for tag -  v2.37.1
pulled commit data for tag -  v2.38.0
pulled commit data for tag -  v2.37.0
pulled commit data for tag -  v2.36.1
pulled commit data for tag -  v2.36.0
pulled commit data for tag -  v2.35.0
pulled commit data for tag -  v2.35.1
pulled commit data for tag -  v2.34.0
pulled commit data for tag -  v2.34.1
pulled commit data for tag -  v2.33.1
pulled commit data for tag -  v2.33.0
pulled commit data for tag -  v2.32.1
pulled commit data for tag -  v2.32.0
pulled commit data for tag -  v2.31.1
pulled commit data for tag -  v2.31.0
pulled commit data for tag -  v2.30.1
pulled commit data for tag -  v2.30.0
pulled commit data for tag -  v2.29.0
pulled commit data for tag -  v2.29.1
pulled commit data for tag -  v2.28.0
pulled commit data for tag -  v2.28.1
pulled commit data for tag -  v2.27.0
pulled commit data for tag -  v2.27.1
pulled commit data for tag -  v2.26.1
pulled commit data for tag -  v2.26.0
pulled commit data for tag -  v2.25.1
pulled commit data for tag -  v2.25.0
pulled commit data for tag -  v2.24.1
pulled commit data for tag -  v2.24.0
pulled commit data for tag -  v2.23.1
pulled commit data for tag -  v2.23.0
pulled commit data for tag -  v2.22.1
pulled commit data for tag -  v2.22.0
fetched 200 commits
pulled commit data for tag -  v2.68.1
pulled commit data for tag -  v2.67.1
pulled commit data for tag -  v2.69.0
pulled commit data for tag -  v2.67.0
pulled commit data for tag -  v2.68.0
error { [Error: 504: Gateway Timeout]
  defaultMessage: 'Gateway Timeout',
  message: '504: Gateway Timeout',
  code: '504' }
stack Error: 504: Gateway Timeout
    at ClientRequest.<anonymous> (/home/s/.nvm/versions/node/v5.9.0/lib/node_modules/github-changes/node_modules/github/index.js:779:26)
    at emitNone (events.js:80:13)
    at ClientRequest.emit (events.js:179:7)
    at TLSSocket.emitTimeout (_http_client.js:582:10)
    at TLSSocket.g (events.js:273:16)
    at emitNone (events.js:80:13)
    at TLSSocket.emit (events.js:179:7)
    at TLSSocket.Socket._onTimeout (net.js:328:8)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)

```

**Comment by lalitkapoor** [comment]
@simov are you still seeing this? I'm not able to reproduce locally w/the requests library. I'm getting a change log generated successfully: https://gist.github.com/lalitkapoor/52e6c837ae38320b88c1adf5962d91a5

Potentially issues with github?

**Comment by simov** [comment]
I built the Changelog for the past 3 releases sort of manually, with a patched version of github-changes that limits the requests made. I doubt that it is a problem with github, because the issue spanned through multiple days. Will report back any new findings.

**Comment by saeedtabrizi** [comment]
Hi @lalitkapoor , @simov I have same problem what can i do ? is there any patch or trick to resolve it ?
